schedules:
- cron: "0 6 * * *"
  displayName: Website update
  branches:
    include:
    - master

# Disable CI trigger (don't run on commits)
trigger: none
# and don't run on Pull Requests
pr: none

pool:
  vmImage: 'ubuntu-20.04'

jobs:
  - job: generate_website
    steps:
    - checkout: self
      persistCredentials: true
      clean: true

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'

    - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: ~/.ssh/known_hosts
        sshPublicKey: $(public_deploy_key)
        sshKeySecureFile: deploy_key

    - script: |
        pip install --upgrade pip
        pip install --upgrade -r requirements_web.txt
      displayName: 'Install requirements'

    - script: . setup/git-setup.sh
      displayName: 'Git setup'

    - script: python3 website-generator/generator.py --config ./setup/config.json
      displayName: 'Generate website'

    - script: . setup/git-deploy-website.sh
      displayName: 'Deploy website'
